new Vue({
			el:"#a",
			data:{
				agingThree:[
					{
						id:'',
						billNum:'',
						billMoney:'',
						hasPay:'',
						srepayDate:'',
						repayDate:'',
						billDate:'',
						billState:''
					}
				]
			},
			methods:{
				queryAllBill:function(){
					var _this=this;
					axios.get("/queryAllBill")
					.then(function(response){
						_this.agingThree=response.data.agingThree;
						console.log(_this.agingThree);
					})
				}
			},
			created:function(){
				this.queryAllBill();
			},
	})
