new Vue({
			el:"#a",
			data:{
				bill:[
					{
						billNum:'',
						billMoney:'',
						srepayDate:'',
						hasPay:'',
						repayDate:'',
						billDate:'',
						billState:''
					}
				]
			},
			methods:{
				queryAllBill:function(){
					var _this=this;
					axios.get("/queryAllBill",_this.id)
					.then(function(response){
						_this.bill=response.data.bill;
						console.log(_this.bill);
					})
				}
			},
			created:function(){
				this.queryAllBill();
			},
	})