new Vue({
			el:"#a",
			data:{
				agingThree:[
					{
						id:'',
						transactionDes:'',
						transactionType:'',
						transactionMoney:'',
						transactionTime:'',
						transactionCoin:'',
						payTime:'',
					}
				]
			},
			methods:{
				queryBillDetails:function(){
					var _this=this;
					axios.get("/queryBillDetails")
					.then(function(response){
						_this.agingThree=response.data.agingThree;
						console.log(_this.agingThree);
					})
				}
			},
			created:function(){
				this.queryBillDetails();
			},
	})
