new Vue({
			el:"#a",
			data:{
				agingThree:[
					{
						id:'',
						clientName:'',
						clientIDcard:'',
						cardNum:'',
						agingNum:'',
						agingLines:'',
						agingNper:'',
						agingTime:'',
						agingRate:'',
						agingState:'',
						agingEndTime:''
					}
				],
				pageInfo:{
					pageNum:'',
				}
			},
			methods:{
				queryAllAging:function(){
					alert("123");
					var _this=this;
					axios.get("/queryAllAging")
					.then(function(response){
						_this.agingThree=response.data.agingThree;
						console.log(_this.agingThree);
						alert(_this.agingThree);
					})
				},
				queryAllAgingss(e){
					alert("456");
					var _this=this;
					_this.e=this.e;
					alert(e+"e");
					axios.get("/queryAllAging",_this.pageNum)
					.then(function(response){
						_this.agingThree=response.data.agingThree;
						_this.pageInfo=response.data.pageInfo;
						_this.pageNum=response.data.pageNum;
						console.log(_this.agingThree);
						alert(_this.pageNum);
					})
				}
			},
			created:function(){
				alert("789");
				this.queryAllAging();
			},
	})

